'''
empty message

Revision ID: 174231e97b1b
Revises: 5504a145b17d
Create Date: 2016-01-01 17:55:03.813399
'''

# revision identifiers, used by Alembic.
revision = '174231e97b1b'
down_revision = '5504a145b17d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'network_ipblock_ip', ['address'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'network_ipblock_ip', type_='unique')
    ### end Alembic commands ###
