'''
empty message

Revision ID: 29d9ade4bb7f
Revises: 174231e97b1b
Create Date: 2016-01-04 12:27:12.584824
'''

# revision identifiers, used by Alembic.
revision = '29d9ade4bb7f'
down_revision = '174231e97b1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_ipblock_ip', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'network_ipblock_ip', 'cloud_service', ['service_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'network_ipblock_ip', type_='foreignkey')
    op.drop_column('network_ipblock_ip', 'service_id')
    ### end Alembic commands ###
