"""empty message

Revision ID: 2d9743b39f2d
Revises: None
Create Date: 2015-12-21 20:12:00.036975

"""

# revision identifiers, used by Alembic.
revision = '2d9743b39f2d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_ipblock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('cidr', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Enum('4', '6'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['network_device.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['network_group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_group_id'], ['core_user_group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['core_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network_ipblock_ip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('Used', 'Unused', 'Reserved'), server_default='Unused', nullable=False),
    sa.Column('ipblock_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['network_device.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ipblock_id'], ['network_ipblock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network_ipblock_ip')
    op.drop_table('network_ipblock')
    ### end Alembic commands ###
