'''
empty message

Revision ID: 34e300c142cc
Revises: 29d9ade4bb7f
Create Date: 2016-01-16 14:47:31.274034
'''

# revision identifiers, used by Alembic.
revision = '34e300c142cc'
down_revision = '29d9ade4bb7f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_ipblock_ip', sa.Column('object_id', sa.Integer(), nullable=True))
    op.add_column('network_ipblock_ip', sa.Column('object_type', sa.String(length=128), nullable=True))
    op.drop_constraint(u'network_ipblock_ip_ibfk_3', 'network_ipblock_ip', type_='foreignkey')
    op.drop_constraint(u'network_ipblock_ip_ibfk_1', 'network_ipblock_ip', type_='foreignkey')
    op.drop_column('network_ipblock_ip', 'service_id')
    op.drop_column('network_ipblock_ip', 'device_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_ipblock_ip', sa.Column('device_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('network_ipblock_ip', sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'network_ipblock_ip_ibfk_1', 'network_ipblock_ip', 'network_device', ['device_id'], ['id'])
    op.create_foreign_key(u'network_ipblock_ip_ibfk_3', 'network_ipblock_ip', 'cloud_service', ['service_id'], ['id'])
    op.drop_column('network_ipblock_ip', 'object_type')
    op.drop_column('network_ipblock_ip', 'object_id')
    ### end Alembic commands ###
