'''
empty message

Revision ID: 5504a145b17d
Revises: 2d9743b39f2d
Create Date: 2015-12-21 21:35:48.853393
'''

# revision identifiers, used by Alembic.
revision = '5504a145b17d'
down_revision = '2d9743b39f2d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('network_device', 'config')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_device', sa.Column('config', mysql.VARCHAR(length=16), nullable=False))
    ### end Alembic commands ###
